# Generated by Django 5.2.14 on 2026-05-06 03:07

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('nombre', models.CharField(max_length=120, verbose_name='Nombre')),
                ('codigo', models.CharField(blank=True, max_length=40, verbose_name='Código')),
                ('unidad_medida', models.CharField(choices=[('UN', 'Unidad'), ('KG', 'Kilogramo'), ('GR', 'Gramo'), ('LT', 'Litro'), ('MT', 'Metro'), ('DC', 'Docena'), ('CA', 'Caja')], default='UN', max_length=2, verbose_name='Unidad de medida')),
                ('stock_actual', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='Stock actual')),
                ('stock_minimo', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='Stock mínimo')),
                ('precio_venta', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='Precio de venta')),
                ('costo', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='Costo')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('negocio', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.negocio', verbose_name='Negocio')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='MovimientoStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('tipo', models.CharField(choices=[('INGRESO', 'Ingreso'), ('EGRESO', 'Egreso'), ('AJUSTE', 'Ajuste')], max_length=10, verbose_name='Tipo')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Cantidad')),
                ('motivo', models.CharField(blank=True, max_length=160, verbose_name='Motivo')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
                ('negocio', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.negocio', verbose_name='Negocio')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='stock.producto', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Movimiento de stock',
                'verbose_name_plural': 'Movimientos de stock',
                'ordering': ['-fecha'],
            },
        ),
        migrations.AddConstraint(
            model_name='producto',
            constraint=models.UniqueConstraint(condition=models.Q(('codigo', ''), _negated=True), fields=('negocio', 'codigo'), name='producto_codigo_unico_por_negocio'),
        ),
    ]
