# Generated by Django 5.2.14 on 2026-05-06 07:12

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0002_initial'),
        ('produccion', '0002_alter_receta_rendimiento_produccionrealizada'),
        ('stock', '0001_initial'),
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientostock',
            name='compra_origen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_stock', to='compras.compra', verbose_name='Compra de origen'),
        ),
        migrations.AddField(
            model_name='movimientostock',
            name='produccion_origen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_stock', to='produccion.produccionrealizada', verbose_name='Producción de origen'),
        ),
        migrations.AddField(
            model_name='movimientostock',
            name='venta_origen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_stock', to='ventas.venta', verbose_name='Venta de origen'),
        ),
        migrations.AlterField(
            model_name='movimientostock',
            name='fecha',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha'),
        ),
    ]
