# Generated by Django 5.2.14 on 2026-05-06 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stock", "0002_movimientostock_compra_origen_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="producto",
            name="presentacion",
            field=models.CharField(
                blank=True,
                help_text='Ej: "200 ml", "250 g", "Docena", "Caja x 12". Se muestra en el POS debajo del nombre.',
                max_length=80,
                verbose_name="Presentación",
            ),
        ),
    ]
