# Generated by Django 5.2.14 on 2026-07-11 18:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_negocio_metodo_costeo"),
        ("stock", "0005_producto_tipo_default_venta"),
    ]

    operations = [
        migrations.AddField(
            model_name="producto",
            name="porciones_por_unidad",
            field=models.PositiveSmallIntegerField(
                default=1,
                help_text="Cantidad de porciones en que se puede fraccionar una unidad entera (ej: 4 para una torta, 16 para un budín). Dejar en 1 si el producto no se vende fraccionado.",
                verbose_name="Porciones por unidad",
            ),
        ),
        migrations.CreateModel(
            name="UnidadFisica",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "creado_en",
                    models.DateTimeField(auto_now_add=True, verbose_name="Creado"),
                ),
                (
                    "actualizado_en",
                    models.DateTimeField(auto_now=True, verbose_name="Actualizado"),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("CERRADA", "Cerrada"),
                            ("ABIERTA", "Abierta"),
                            ("AGOTADA", "Agotada"),
                        ],
                        default="CERRADA",
                        max_length=10,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "porciones_restantes",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="Porciones restantes"
                    ),
                ),
                (
                    "negocio",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="core.negocio",
                        verbose_name="Negocio",
                    ),
                ),
                (
                    "producto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="unidades_fisicas",
                        to="stock.producto",
                        verbose_name="Producto",
                    ),
                ),
            ],
            options={
                "verbose_name": "Unidad física",
                "verbose_name_plural": "Unidades físicas",
                "ordering": ["-creado_en"],
            },
        ),
    ]
