# Generated by Django 5.2.14 on 2026-07-11 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stock", "0006_producto_porciones_por_unidad_unidadfisica"),
    ]

    operations = [
        migrations.AddField(
            model_name="producto",
            name="cantidad_minima_mayorista",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text='A partir de esta cantidad en una misma línea de venta se cobra "Precio por mayor" en vez de "Precio de venta" (ej: 6 facturas o más a $700 c/u en vez de $800). Vacío = no aplica precio por mayor.',
                null=True,
                verbose_name="Cantidad mínima por mayor",
            ),
        ),
        migrations.AddField(
            model_name="producto",
            name="precio_mayorista",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text='Precio unitario que se cobra cuando se alcanza la "Cantidad mínima por mayor".',
                max_digits=12,
                null=True,
                verbose_name="Precio por mayor",
            ),
        ),
    ]
