# Generated by Django 5.2.14 on 2026-05-06 22:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="negocio",
            name="modulo_clientes",
            field=models.BooleanField(default=True, verbose_name="Clientes"),
        ),
        migrations.AddField(
            model_name="negocio",
            name="modulo_compras",
            field=models.BooleanField(default=True, verbose_name="Compras"),
        ),
        migrations.AddField(
            model_name="negocio",
            name="modulo_gastos",
            field=models.BooleanField(default=True, verbose_name="Gastos fijos"),
        ),
        migrations.AddField(
            model_name="negocio",
            name="modulo_produccion",
            field=models.BooleanField(
                default=True, verbose_name="Producción y recetas"
            ),
        ),
        migrations.AddField(
            model_name="negocio",
            name="onboarding_completado",
            field=models.BooleanField(
                default=False, verbose_name="Onboarding completado"
            ),
        ),
        migrations.AddField(
            model_name="negocio",
            name="trial_hasta",
            field=models.DateField(
                blank=True,
                help_text="Vacío = sin restricción. Pasada la fecha el negocio queda en solo-lectura.",
                null=True,
                verbose_name="Trial hasta",
            ),
        ),
        migrations.CreateModel(
            name="ActividadNegocio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateTimeField(auto_now_add=True)),
                ("modulo", models.CharField(max_length=50)),
                ("accion", models.CharField(max_length=200)),
                (
                    "negocio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="actividades",
                        to="core.negocio",
                    ),
                ),
            ],
            options={
                "verbose_name": "Actividad",
                "verbose_name_plural": "Actividades",
                "ordering": ["-fecha"],
            },
        ),
    ]
