# Generated by Django 5.2.14 on 2026-05-08 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_negocio_modulos_trial_actividad"),
    ]

    operations = [
        migrations.AddField(
            model_name="negocio",
            name="metodo_costeo",
            field=models.CharField(
                choices=[
                    ("MANUAL", "Manual (alerta al cambiar)"),
                    ("PPP", "Promedio ponderado automático"),
                ],
                default="MANUAL",
                help_text="MANUAL: muestra alerta cuando el precio de compra difiere del costo. PPP: actualiza el costo automáticamente con promedio ponderado.",
                max_length=10,
                verbose_name="Método de costeo",
            ),
        ),
    ]
