# Generated by Django 5.2.14 on 2026-06-29 15:11

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_negocio_metodo_costeo"),
        ("stock", "0005_producto_tipo_default_venta"),
        ("ventas", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PresentacionVenta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "creado_en",
                    models.DateTimeField(auto_now_add=True, verbose_name="Creado"),
                ),
                (
                    "actualizado_en",
                    models.DateTimeField(auto_now=True, verbose_name="Actualizado"),
                ),
                ("nombre", models.CharField(max_length=80, verbose_name="Nombre")),
                (
                    "factor",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Unidades de stock base que descuenta esta presentación.",
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                        verbose_name="Factor de stock",
                    ),
                ),
                (
                    "precio",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                        verbose_name="Precio de venta",
                    ),
                ),
                ("activo", models.BooleanField(default=True, verbose_name="Activo")),
                (
                    "negocio",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="core.negocio",
                        verbose_name="Negocio",
                    ),
                ),
                (
                    "producto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="presentaciones",
                        to="stock.producto",
                        verbose_name="Producto",
                    ),
                ),
            ],
            options={
                "verbose_name": "Presentación de venta",
                "verbose_name_plural": "Presentaciones de venta",
                "ordering": ["producto", "factor"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("negocio", "producto", "nombre"),
                        name="presentacion_nombre_unico_por_producto_negocio",
                    )
                ],
            },
        ),
    ]
