# Generated by Django 5.2.14 on 2026-06-29 15:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ventas", "0002_presentacionventa"),
    ]

    operations = [
        migrations.AddField(
            model_name="itemventa",
            name="presentacion",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="items_venta",
                to="ventas.presentacionventa",
                verbose_name="Presentación de venta",
            ),
        ),
    ]
