# Generated by Django 5.2.14 on 2026-07-11 18:03

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_negocio_metodo_costeo"),
        ("stock", "0006_producto_porciones_por_unidad_unidadfisica"),
        ("ventas", "0003_itemventa_presentacion"),
    ]

    operations = [
        migrations.CreateModel(
            name="ComboItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "creado_en",
                    models.DateTimeField(auto_now_add=True, verbose_name="Creado"),
                ),
                (
                    "actualizado_en",
                    models.DateTimeField(auto_now=True, verbose_name="Actualizado"),
                ),
                (
                    "cantidad",
                    models.PositiveSmallIntegerField(
                        default=1,
                        help_text="Cantidad de unidades enteras de este producto que incluye el combo.",
                        verbose_name="Unidades enteras",
                    ),
                ),
                (
                    "porciones",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="Completar en vez de 'Unidades enteras' si el combo incluye solo una fracción de este producto (ej: mitad = la mitad de sus porciones totales).",
                        null=True,
                        verbose_name="Porciones",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ítem de combo",
                "verbose_name_plural": "Ítems de combo",
            },
        ),
        migrations.AddField(
            model_name="itemventa",
            name="porciones",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="Si se vende una fracción puntual del producto (ej: 'media torta' pedida por el cliente) en vez de una unidad/presentación completa. No combinar con 'Combo'.",
                null=True,
                verbose_name="Porciones",
            ),
        ),
        migrations.AlterField(
            model_name="itemventa",
            name="producto",
            field=models.ForeignKey(
                blank=True,
                help_text="Vacío si el ítem es un Combo (se completa 'Combo' en su lugar).",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="items_venta",
                to="stock.producto",
                verbose_name="Producto",
            ),
        ),
        migrations.CreateModel(
            name="Combo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "creado_en",
                    models.DateTimeField(auto_now_add=True, verbose_name="Creado"),
                ),
                (
                    "actualizado_en",
                    models.DateTimeField(auto_now=True, verbose_name="Actualizado"),
                ),
                ("nombre", models.CharField(max_length=120, verbose_name="Nombre")),
                (
                    "precio",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                        verbose_name="Precio del combo",
                    ),
                ),
                ("activo", models.BooleanField(default=True, verbose_name="Activo")),
                (
                    "negocio",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="core.negocio",
                        verbose_name="Negocio",
                    ),
                ),
            ],
            options={
                "verbose_name": "Combo",
                "verbose_name_plural": "Combos",
                "ordering": ["nombre"],
            },
        ),
        migrations.AddField(
            model_name="itemventa",
            name="combo",
            field=models.ForeignKey(
                blank=True,
                help_text="Completar en vez de 'Producto' cuando el ítem es un combo de varios productos.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="items_venta",
                to="ventas.combo",
                verbose_name="Combo",
            ),
        ),
        migrations.AddConstraint(
            model_name="itemventa",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("combo__isnull", True), ("producto__isnull", False)),
                    models.Q(("combo__isnull", False), ("producto__isnull", True)),
                    _connector="OR",
                ),
                name="itemventa_producto_xor_combo",
            ),
        ),
        migrations.AddField(
            model_name="comboitem",
            name="combo",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="ventas.combo",
                verbose_name="Combo",
            ),
        ),
        migrations.AddField(
            model_name="comboitem",
            name="negocio",
            field=models.ForeignKey(
                editable=False,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="core.negocio",
                verbose_name="Negocio",
            ),
        ),
        migrations.AddField(
            model_name="comboitem",
            name="producto",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="items_combo",
                to="stock.producto",
                verbose_name="Producto",
            ),
        ),
        migrations.AddConstraint(
            model_name="combo",
            constraint=models.UniqueConstraint(
                fields=("negocio", "nombre"), name="combo_nombre_unico_por_negocio"
            ),
        ),
    ]
