# Generated by Django 5.2.14 on 2026-05-06 07:12

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('produccion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receta',
            name='rendimiento',
            field=models.DecimalField(decimal_places=2, default=Decimal('1'), help_text='Cantidad de producto resultante que produce esta receta (un lote).', max_digits=12, verbose_name='Rendimiento'),
        ),
        migrations.CreateModel(
            name='ProduccionRealizada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('cantidad_lotes', models.DecimalField(decimal_places=2, default=Decimal('1'), help_text='Cuántas veces se ejecuta la receta. Ej: 2 = doble de ingredientes, doble de rendimiento.', max_digits=10, verbose_name='Cantidad de lotes')),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de producción')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('negocio', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.negocio', verbose_name='Negocio')),
                ('receta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='producciones', to='produccion.receta', verbose_name='Receta')),
            ],
            options={
                'verbose_name': 'Producción realizada',
                'verbose_name_plural': 'Producciones realizadas',
                'ordering': ['-fecha'],
            },
        ),
    ]
