# Generated by Django 5.2.14 on 2026-05-06 03:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MovimientoCaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha')),
                ('tipo', models.CharField(choices=[('INGRESO', 'Ingreso'), ('EGRESO', 'Egreso')], max_length=10, verbose_name='Tipo')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monto')),
                ('concepto', models.CharField(max_length=200, verbose_name='Concepto')),
                ('metodo_pago', models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('DEBITO', 'Débito'), ('CREDITO', 'Crédito'), ('TRANSFERENCIA', 'Transferencia'), ('MP', 'Mercado Pago'), ('OTRO', 'Otro')], default='EFECTIVO', max_length=20, verbose_name='Método de pago')),
            ],
            options={
                'verbose_name': 'Movimiento de caja',
                'verbose_name_plural': 'Movimientos de caja',
                'ordering': ['-fecha'],
            },
        ),
    ]
