# Generated by Django 5.2.14 on 2026-05-06 03:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('caja', '0002_initial'),
        ('core', '0001_initial'),
        ('gastos', '0001_initial'),
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientocaja',
            name='gasto_origen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_caja', to='gastos.gastofijo', verbose_name='Gasto fijo de origen'),
        ),
        migrations.AddField(
            model_name='movimientocaja',
            name='negocio',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.negocio', verbose_name='Negocio'),
        ),
        migrations.AddField(
            model_name='movimientocaja',
            name='venta_origen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_caja', to='ventas.venta', verbose_name='Venta de origen'),
        ),
    ]
